# Generated by Django 2.0.13 on 2021-09-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='covid_story',
            fields=[
                ('story_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
    ]
